version: "3"
services:
  user:
    build:
      context: .
    image: "fikridulumina/user-services:dev-1.0.0"
    container_name: app_user
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - "./:/opt/app"
    depends_on:
      - dbUser
    networks:
      - user
  dbUser:
    image: "mysql:5.7"
    container_name: db_user
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
    ports:
      - "${DB_PORT}"
    volumes:
      - "./my-db:/var/lib/mysql"
    networks:
      - user
  dbUserPma:
    depends_on:
      - dbUser
    image: phpmyadmin/phpmyadmin
    container_name: dbUserPma
    restart: always
    ports:
      - "3031:80"
    environment:
      PMA_HOST: dbUser
    networks:
      - user

networks:
  user: null
